stages:
  - pre_check
  - scan_build
  - build_openocd
  - build_idf4.x
  - build_idf5.x
  - build_idf_master
  - build_nuttx
  - test_idf4.x
  - test_idf5.x
  - test_idf_master
  - test_windows
  - test_nuttx
  - coverage
  - sanitizer_tests
  - sanitizer_checks
  - deploy
  - private_deploy
  - pre_release
  - release_stage1
  - release_submit
  - update_idf_tools

image: $CI_DOCKER_REGISTRY/openocd-ci-env:1

variables:

  #
  # System environment

  # Common parameters for the 'make' during CI tests
  MAKEFLAGS: "-j4 --no-keep-going"

  GCOV_BUILD_OPTS: ""

  # OpenOCD configuration options
  OPENOCD_CONFIGURE_OPTS: "--disable-doxygen-html --disable-doxygen-pdf --enable-ftdi --enable-jlink --enable-ulink"

  # GitHub Tool options
  GITHUB_USER: "${GH_USER}"
  GITHUB_REPO: "${GH_REPO}"
  GITHUB_TOKEN: "${GH_TOKEN}"

  #
  # CI settings

  # GIT_STRATEGY is not defined here, an option from "CI / CD Settings"- "General pipelines" is used.
  GIT_SUBMODULE_STRATEGY: none

  #
  # Customization of jobs

  DIST_ART_DIR: "dist"
  DIST_INSTALLED_DIR: "${CI_PROJECT_NAME}"
  ARCHIVE_TOOL: "tar czf"
  ARCHIVE_EXT: "tar.gz"
  RELEASE_DESC: "New release"

  #
  # default variables
  ESP_TOOLCHAIN: "${ESP_MASTER_TOOLCHAIN_VER}"
  TOOLCHAIN_PREFIX: "xtensa-esp32"
  CHIP_NAME: "esp32"

# prefix should be like a $CI_PROJECT_NAME, but we cannot use variable here
.release_tag_filter: &release_tag_filter
  only:
    - /^v[0-9].*$/
    - /^openocd-esp32-.*$/

.release_binaries: &release_binaries
  needs:
    - job: build_linux
    - job: build_linux_armhf
    - job: build_linux_armel
    - job: build_linux_arm64
    - job: build_windows
    - job: osx_code_sign

.release_submit_action: &release_submit_action
  image: espressif/github-hub:2
  when: manual
  allow_failure: true
  before_script:
    - set -o errexit; set -o pipefail; set -o nounset
    - test "${DEBUG_SHELL:-''}" = "1" && set -x
    - git remote remove github || true
    - git remote add github ${GH_REPO_HTTPS}
  variables:
    GIT_STRATEGY: fetch
    GH_REL_TAG: ${CI_COMMIT_TAG}
    SHA256_FILE: openocd-esp32-${CI_COMMIT_TAG}-checksum.sha256

before_script:
  - set -o errexit; set -o pipefail; set -o nounset
  - test "${DEBUG_SHELL:-''}" = "1" && set -x

.do_osx_code_sign: &do_osx_code_sign |
  tar -xzf ${DIST_ART_DIR}/$ARCHIVE_NAME -C ${DIST_ART_DIR} && rm ${DIST_ART_DIR}/$ARCHIVE_NAME
  export TARGET_BINARY="${DIST_ART_DIR}/openocd-esp32/bin/openocd"
  $PWD/tools/codesign.sh
  $PWD/tools/notarize.sh
  pushd ${DIST_ART_DIR}
  ${ARCHIVE_TOOL} ${ARCHIVE_NAME} openocd-esp32/
  rm -r openocd-esp32/
  popd

osx_code_sign:
  stage: pre_release
  <<: *release_tag_filter
  when: on_success
  tags:
    - macos_shell
  dependencies:
   - build_macos
   - build_macos_arm64
  artifacts:
    paths:
      - ${DIST_ART_DIR}
  script:
    - ARCHIVE_NAME=$(cat ${DIST_ART_DIR}/dist_name_macos)
    - *do_osx_code_sign
    - ARCHIVE_NAME=$(cat ${DIST_ART_DIR}/dist_name_macos-arm64)
    - *do_osx_code_sign

release_tag_draft:
  stage: release_stage1
  tags: [ "amd64", "internet" ]
  <<: *release_tag_filter
  <<: *release_submit_action
  <<: *release_binaries
  script:
    - git remote remove github || true
    - git remote add github ${GH_REPO_HTTPS}
    - hub release show ${GH_REL_TAG} || { echo "Please create a release on GitHub with ${GH_REL_TAG} tag at first"; exit 1; }
    # List of archives
    - DIST_DIR=dist
    - FILES=$(find ${DIST_DIR} -name dist_name_\* -exec cat {} \+)
    - cd ${DIST_DIR}
    - ls -l $FILES
    # Generate checksum file
    - >
      for n in $FILES; do
        sz=$(stat -c%s "${n}") >> ${SHA256_FILE};
        printf "# %s: %s bytes\n" "${n}" "${sz}" >> ${SHA256_FILE};
        sha256sum -b "${n}" >> ${SHA256_FILE};
      done
    # Append FILES with checksum file
    - FILES=$(echo -e "${FILES}\n${SHA256_FILE}")
    - ls -l $FILES
    # Upload archives
    - for n in ${FILES}; do hub release edit -m "" -a "${n}" "${GH_REL_TAG}"; done

Release_tag_submit:
  stage: release_submit
  tags: [ "amd64", "internet" ]
  <<: *release_tag_filter
  <<: *release_submit_action
  script:
    - hub release create -m "${RELEASE_DESC}" ${GH_REL_TAG}

Pre-Release_tag_submit:
  stage: release_submit
  tags: [ "amd64", "internet" ]
  <<: *release_tag_filter
  <<: *release_submit_action
  script:
    - hub release create --prerelease -m "${RELEASE_DESC}" ${GH_REL_TAG}

Delete_tag_release:
  stage: release_submit
  tags: [ "amd64", "internet" ]
  <<: *release_tag_filter
  <<: *release_submit_action
  script:
    - hub release delete ${GH_REL_TAG}

.use_ci_tools: &use_ci_tools |
  curl -sSL ${CIT_LOADER_URL} -o cit_loader.sh && sh cit_loader.sh
  source citools/import_functions

upload_to_http:
  stage: private_deploy
  when: manual
  tags: [ "deploy", "shiny" ]
  only:
    - master
  allow_failure: true
  dependencies:
    - build_linux_armhf
  artifacts:
    reports:
      dotenv: build.env
  before_script:
    - *use_ci_tools
  script:
    - cit_add_ssh_key "${HTTP_UPLOAD_KEY}"
    - ARCHIVE_NAME=$(cat ${DIST_ART_DIR}/dist_name_linux-armhf)
    - pushd ${DIST_ART_DIR}
    - scp ${ARCHIVE_NAME} ${HTTP_UPLOAD_DIR}/openocd/
    - popd
    - OOCD_DISTRO_URL=${HTTP_PUBLIC_DIR}/openocd/${ARCHIVE_NAME}
    - echo "Archive was published there '${OOCD_DISTRO_URL}'"
    - echo "NEW_OOCD_DISTRO_URL=${OOCD_DISTRO_URL}" >> build.env

test_idf_master_examples:
  stage: pre_release
  when: manual
  only:
    - master
  allow_failure: true
  variables:
    OOCD_DISTRO_URL: ${NEW_OOCD_DISTRO_URL}
    BOT_LABEL_EXAMPLE_TEST: "1"
  needs:
    - job: upload_to_http
      artifacts: true
  trigger:
    project: espressif/esp-idf
    strategy: depend

test_idf4.x_examples:
  stage: pre_release
  when: manual
  only:
    - master
  allow_failure: true
  variables:
    OOCD_DISTRO_URL: ${NEW_OOCD_DISTRO_URL}
  needs:
    - job: upload_to_http
      artifacts: true
  trigger:
    project: espressif/esp-idf
    branch: ${TEST_APP_IDF4_X_RELEASE_BRANCH}
    strategy: depend

create_coverage_reports:
  stage: coverage
  image: $CI_DOCKER_REGISTRY/openocd-ci-env:1
  tags:
    - build
  allow_failure: true
  artifacts:
    paths:
      - dist/lcov_all_report.tar.gz
      - cov_infos/metrics.txt
      - cov_infos/cobertura.xml
    reports:
      metrics: cov_infos/metrics.txt
      coverage_report:
        coverage_format: cobertura
        path: cov_infos/cobertura.xml
    when: always
    expire_in: 1 week
  needs:
    - job: tests_armhf_esp32_idf4.x
    - job: tests_armhf_esp32_idf4.x_flash_encrypted
    - job: tests_armhf_esp32s2_idf4.x
    - job: tests_armhf_esp32s2_idf4.x_flash_encrypted
    - job: tests_armhf_esp32s3_idf4.x
    - job: tests_armhf_esp32c3_idf4.x
    - job: tests_armhf_esp32c3_idf4.x_flash_encrypted
    #- job: tests_armhf_esp32_solo_idf4.x
    - job: tests_armhf_esp32_flash_encrypted
    - job: tests_armhf_esp32s2
    - job: tests_armhf_esp32s2_flash_encrypted
    - job: tests_armhf_esp32s3
    - job: tests_armhf_esp32c3_builtin_usb_jtag
    - job: tests_armhf_esp32c3_flash_encrypted
    - job: tests_armhf_esp32
    #- job: tests_armhf_esp32_solo
    - job: tests_armhf_esp32c3
    - job: tests_armhf_esp32c2
    - job: test_nuttx_esp32
    - job: test_nuttx_esp32s2
    - job: test_nuttx_esp32s3
    - job: test_nuttx_esp32c3
    - job: tests_armhf_esp32c6_builtin_usb_jtag
  script:
    - mkdir -p cov_infos
    - mkdir -p dist
    # Below lines copies all .info files into cov_infos folder
    - >
      folder_list=$(ls -d build_test_app*);
      for each_folder in $folder_list ;
      do
      cp ${each_folder}/*.info cov_infos;
      done
    - ls -la cov_infos/
    # Creating a html report of coverage files.
    - genhtml --ignore-errors source cov_infos/*.info -o lcov_html_report/
    - tar czf dist/lcov_all_report.tar.gz lcov_html_report/
    # Below lines collecting all coverage file names with '-a' flag for lcov merge command.
    - >
      FILES="" ;
      for each_file in cov_infos/*.info ;
      do
      FILES+=" -a ${each_file}" ;
      done
    - lcov ${FILES} -o cov_infos/merged.info
    # Line in below creates a txt file from merged coverage file which includes coverage percentages.
    - lcov --rc lcov_list_width=150 --list cov_infos/merged.info > cov_infos/metrics_input.txt
    - python3 tools/list_to_metrics.py --file cov_infos/metrics_input.txt
    - lcov_cobertura cov_infos/merged.info -o cov_infos/cobertura.xml

update_idf_tools:
  stage: update_idf_tools
  when: manual
  allow_failure: true
  <<: *release_tag_filter
  variables:
    TOOL_NAME: OpenOCD
    TOOL_MEMBERS: openocd-esp32
    TOOL_VERSION: ${CI_COMMIT_TAG}
    TOOL_SHA256_URL: https://github.com/espressif/openocd-esp32/releases/download/${CI_COMMIT_TAG}/openocd-esp32-${CI_COMMIT_TAG}-checksum.sha256
  trigger:
    project: idf/idf-tools-updater
    strategy: depend

include:
  - '.gitlab/ci/util.yml'
  - '.gitlab/ci/build.yml'
  - '.gitlab/ci/build-test-app.yml'
  - '.gitlab/ci/test.yml'
  - '.gitlab/ci/test-sanitizers.yml'
  - '.gitlab/ci/pre-check.yml'

