name: Build OpenOCD for Windows, MacOS, and Linux

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build-macos-x86:
    runs-on: macos-13
    steps:
      - name: Ensure architecture is x86_64
        run: |
          if [[ "$(uname -m)" != "x86_64" ]]; then
            echo "Error: Expected x86_64 architecture but got $(uname -m)" >&2
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: install deps
        run: brew install automake texinfo coreutils
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: macos-x86

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Ensure architecture is arm64
        run: |
          if [[ "$(uname -m)" != "arm64" ]]; then
            echo "Error: Expected arm64 architecture but got $(uname -m)" >&2
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: install deps
        run: brew install automake libtool texinfo coreutils
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: macos-arm64

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get install libudev-dev systemd --force-yes -y
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: linux

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get install libtool-bin libudev-dev gcc-mingw-w64-i686
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: windows
